# Generated by Django 4.1.7 on 2023-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='creador',
            field=models.CharField(max_length=100),
        ),
    ]
