# Generated by Django 4.1.7 on 2023-05-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0002_alter_mensaje_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeCharla.sala')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeCharla.sesion')),
            ],
        ),
    ]
