# Generated by Django 4.1.7 on 2023-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0003_ultimavisita'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimavisita',
            name='mensajes_no_leidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
