# Generated by Django 4.1.7 on 2023-05-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0004_ultimavisita_mensajes_no_leidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='cookie',
            new_name='cookie_user',
        ),
    ]
