# Generated by Django 4.1.7 on 2023-06-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0005_rename_cookie_sesion_cookie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='votos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeCharla.sala')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeCharla.sesion')),
            ],
        ),
    ]
