# Generated by Django 4.1.7 on 2023-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0006_sala_votos_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='megusta',
            field=models.BooleanField(default=False),
        ),
    ]
