# Generated by Django 4.1.7 on 2023-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0007_sala_megusta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='megusta',
        ),
        migrations.AddField(
            model_name='voto',
            name='megusta',
            field=models.BooleanField(default=False),
        ),
    ]
