# Generated by Django 4.1.7 on 2023-06-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0009_alter_mensaje_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeCharla.sesion'),
        ),
    ]
