# Generated by Django 4.1.7 on 2023-06-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0010_alter_sala_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeCharla.configuracion'),
        ),
    ]
