# Generated by Django 4.1.7 on 2023-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0011_remove_sesion_nombre_alter_mensaje_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='creador',
            field=models.CharField(max_length=100),
        ),
    ]
