# Generated by Django 4.1.7 on 2023-06-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeCharla', '0012_alter_mensaje_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='imagen',
        ),
    ]
